import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>HobbyFinder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/../../../../hobbies-icon.png" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to HobbyFinder&nbsp;
        </h1>
        &nbsp;
        <div className={styles.grid}>
          <Link href="/posts/music" > 
            <a className={styles.card}> <h2>Cultural/Educational</h2> </a>
          </Link>
  
          <Link href="/posts/geography" >
          <a className={styles.card}> <h2>Arts & Crafts</h2> </a>
          </Link>

          <Link href="/posts/history" >
          <a className={styles.card}> <h2>Social/Community</h2> </a>
          </Link>

          <Link href="/posts/general" >
          <a className={styles.card}> <h2>Lifestyle</h2> </a>
          </Link>

          <Link href="/posts/setting" >
          <a className={styles.card}> <h2>Sports</h2> </a>
          </Link>
            
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
